name: "Publish artifact"
description: "Generic action to publish artifacts"

inputs:
  jf_url:
    required: true
  jf_user:
    required: true
  jf_password:
    required: true
  repository_type:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3.3.0
      env:
        JF_URL: ${{ inputs.jf_url }}        
        JF_USER: ${{ inputs.jf_user }}
        JF_PASSWORD: ${{ inputs.jf_password }}
    - name: Ping Artifactory
      run: |
        jf rt ping
        echo "${{ github.ref_name }}"
      shell: bash
    # - name: Publish artifact
    #   if: ${{ inputs.repository_type == "npm" }}
    #   run: |
    #     echo ${{ github.ref_name }}
        

